- CHANGELOG.md
- README.md
Update links given we now know the URL of this extension on the Chrome Web Store.
> doc: updated links to Chrome Webstore now we are published

- .releaserc
- package.json
- public/manifest.json
- src/components/Popup/Popup.tsx
- src/options.tsx
- src/utils/UserAgentHelper.ts
> fix: Obtain version of this extension from the manifest

- src/utils/Constants.ts
- src/utils/PageParsing/RubyGems.test.ts
- src/utils/PageParsing/RubyGems.ts
- src/utils/PageParsing/testdata/rubygems-platform.html
> fix: incorrect PURL derived for RubyGems when platform was present #28

- .circleci/config.yml
- src/components/Options/IQServer/IQServerOptionsPage.tsx
- src/components/Options/Options.tsx
- src/content.ts
- src/extension_service_worker.ts
- src/utils/Analytics.ts
- src/utils/AnalyticsConfg.ts
> feat: add basic usage analytics collection

- .releaserc
- scripts/edge-webstore.js
> ci: prevent patch releases to Microsoft Edge Webstore

- src/utils/Constants.ts
- src/utils/PageParsing/Conanio.test.ts
- src/utils/PageParsing/testdata/conanio-libxft-2.3.6.html
- src/utils/PageParsing/testdata/conanio-libxft-2.3.8.html
- src/utils/PageParsing/testdata/conanio-proj-8.2.1.html
- src/utils/PageParsing/testdata/update-test-data.sh
Fix for #69
`conan.io` has changes it's URL structure and page HTML requiring updates to this extension.
> fix: update to handle URL and HTML changes for conan.io 

- src/components/Popup/IQServer/RemediationPage/AllVersionsPage/AllVersionsDetails/AllVersionsDetails.tsx
Fixes #80.  We now correctly format the age dates in the versions list.
> fix: #80 - fix the date formats when in between groupings

- src/utils/PageParsing/PyPI.test.ts
- src/utils/PageParsing/PyPI.ts
- src/utils/PageParsing/testdata/pypi-numpy-1.14.0.html
> fix: detect source extension format for PyPi rather than always assuming `tar.gz`

- src/utils/PageParsing/CentralSonatypeCom.test.ts
- src/utils/PageParsing/CentralSonatypeCom.ts
- src/utils/PageParsing/testdata/central-s-c-android.html
> fix: detect packaging format for Maven Central from POM XML rather than always assuming `jar`

- src/utils/PageParsing/CentralSonatypeCom.test.ts
- src/utils/PageParsing/CentralSonatypeCom.ts
- src/utils/PageParsing/testdata/central-s-c-log4j-parent.html
- src/utils/PageParsing/testdata/central-s-c-scalacheck-bundle.html
> fix: force Maven Central components with packaging `bundle` to be `jar`

- src/utils/PageParsing/CentralSonatypeCom.test.ts
- src/utils/PageParsing/CentralSonatypeCom.ts
- src/utils/PageParsing/testdata/central-s-c-commons-io.html
- src/utils/PageParsing/testdata/update-test-data.sh
> fix: update for Maven Central changes

- README.md
> doc: confirm IQ version supported and tested

- src/utils/PageParsing/NPM.ts
> fix: more accurate DOM parsing for NPMJS which resolves navigation during brower history buttons

- src/messages/IqMessages.ts
- src/types/Message.ts
> fix: not all versions reported for some Python Packages #113

- public/_locales/en/messages.json
- public/_locales/es/messages.json
- public/_locales/fi/messages.json
- public/_locales/fr/messages.json
- public/_locales/ko/messages.json
- public/_locales/pt_BR/messages.json
- public/_locales/pt_PT/messages.json
- public/_locales/zh_CN/messages.json
- public/_locales/zh_TW/messages.json
- src/components/Popup/IQServer/ComponentInfoPage/ComponentInfoPage.tsx
Add Integrity and Hygiene ratings if present.
Resolves #123 
Both Integrity and Hygiene: https://central.sonatype.com/artifact/org.apache.struts/struts2-core/6.1.2
Hygiene Only: https://central.sonatype.com/artifact/org.apache.struts/struts2-core/2.5.29
Integrity Only: https://www.npmjs.com/package/express/v/4.19.2
> feat: add Integrity and Hygiene ratings if present

- public/_locales/ca/messages.json
- public/_locales/de/messages.json
- public/_locales/el/messages.json
- public/_locales/es/messages.json
- public/_locales/fi/messages.json
- public/_locales/fr/messages.json
- public/_locales/pt_BR/messages.json
- public/_locales/pt_PT/messages.json
> fix: update Extension Description to be 132 chars or less

- README.md
- package.json
- public/_locales/ca/messages.json
- public/_locales/de/messages.json
- public/_locales/el/messages.json
- public/_locales/en/messages.json
- public/_locales/es/messages.json
- public/_locales/fi/messages.json
- public/_locales/fr/messages.json
- public/_locales/ko/messages.json
- public/_locales/pt_BR/messages.json
- public/_locales/pt_PT/messages.json
- public/_locales/zh_CN/messages.json
- public/_locales/zh_TW/messages.json
- public/images/golden-star.svg
- src/components/Popup/ExtensionPopup.tsx
- src/components/Popup/IQServer/RemediationPage/RemediationDetails/RemediationDetails.tsx
- src/components/Popup/IQServer/RemediationPage/RemediationDetails/SuggestedVersionChange.tsx
- src/components/Popup/IQServer/RemediationPage/RemediationPage.tsx
- src/context/ExtensionPopupContext.ts
- src/messages/IqMessages.ts
- src/types/Message.ts
- src/utils/Constants.ts
- yarn.lock
> feat: display 🏆 Golden Version when supported

- .github/workflows/page-parsing.yaml
> chore(ci): add CI workflow to test page parsing weekly

- src/extension_service_worker.ts
- src/utils/Analytics.ts
Partial implementation of #147
> fix: analytics events not always well formed

- src/components/Popup/ExtensionPopup.tsx
- src/content.ts
- src/extension_service_worker.ts
- src/index.tsx
- src/logger/Logger.ts
- src/options.tsx
- src/service/tab-on.ts
- src/settings/extension-configuration-react.ts
Resolves:
- #161 
- #162
- #160
> feat: use Session Storage, not Local Storage

- .github/workflows/release.yml
- package-lock.json
- package.json
- scripts/edge-webstore.js
> fix: Edge Webstore publishing

- src/service/handlers/tab-on.ts
Resolves #241 
FYI @maurycupitt
> feat: Improvement to guard against duplicate Component Evaluation cals

- src/service/index.ts
Resolves #13 
FYI @maurycupitt
> feat: Improvement to not broadcast state to all clients when a new client connects
